Package.describe({
  name: 'meteor-gazelle:theme',
  version: '0.0.1',
  summary: 'meteor-gazelle default theme',
  documentation: 'README.md',
  git: 'https://github.com/meteor-gazelle/meteor-gazelle.git'
});

Npm.depends({
  'bourbon': '4.2.3',
  'bourbon-neat': '1.7.2',
  'node-normalize-scss': '1.0.3',
  'font-awesome': '4.3.0'
});

Package.onUse(function (api) {
  api.versionsFrom('1.1.0.2');

  api.use([
    'fourseven:scss@3.3.3_1',
  ]);

  api.addFiles([
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/_bourbon.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/settings/_px-to-em.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/settings/_asset-pipeline.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/settings/_prefixer.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_contains.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_modular-scale.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_is-size.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_unpack.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_is-number.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_is-light.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_px-to-em.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_strip-units.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_tint.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_is-length.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_px-to-rem.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_transition-property-name.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_assign-inputs.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_shade.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/functions/_contains-falsy.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_radial-arg-parser.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_radial-positions-parser.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_str-to-num.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_shape-size-stripper.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_render-gradients.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_font-source-declaration.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_linear-gradient-parser.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_linear-angle-parser.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_linear-side-corner-parser.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_linear-positions-parser.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_directional-values.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_convert-units.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_gradient-positions-parser.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/helpers/_radial-gradient-parser.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_border-color.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_ellipsis.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_triangle.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_border-width.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_clearfix.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_padding.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_buttons.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_font-stacks.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_text-inputs.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_size.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_border-style.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_word-wrap.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_position.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_border-radius.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_retina-image.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_prefixer.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_hide-text.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_timing-functions.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/addons/_margin.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_border-image.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_background.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_filter.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_linear-gradient.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_selection.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_transition.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_animation.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_text-decoration.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_user-select.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_font-feature-settings.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_hyphens.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_calc.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_transform.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_background-image.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_columns.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_appearance.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_backface-visibility.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_keyframes.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_flex-box.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_perspective.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_font-face.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_radial-gradient.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_hidpi-media-query.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_image-rendering.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/css3/_placeholder.scss',
    '.npm/package/node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecated-upcoming.scss',
    '.npm/package/node_modules/bourbon-neat/app/assets/stylesheets/_neat.scss',
    '.npm/package/node_modules/font-awesome/scss/_variables.scss',
    '.npm/package/node_modules/font-awesome/scss/_mixins.scss',
    '.npm/package/node_modules/font-awesome/scss/_path.scss',
    '.npm/package/node_modules/node-normalize-scss/_normalize.scss',
    'stylesheets/_font-awesome-custom.scss',
    'stylesheets/_fonts.scss',
    'stylesheets/_layout.scss',
    'stylesheets/_mixins.scss',
    'stylesheets/_public.scss',
    'stylesheets/_useraccounts.scss',
    'stylesheets/_variables.scss',
    'stylesheets/core.scss',
    'stylesheets/default.scss',
    'stylesheets/public.scss'
  ], 'client');

  api.addAssets([
    '.npm/package/node_modules/font-awesome/fonts/FontAwesome.otf',
    '.npm/package/node_modules/font-awesome/fonts/fontawesome-webfont.eot',
    '.npm/package/node_modules/font-awesome/fonts/fontawesome-webfont.svg',
    '.npm/package/node_modules/font-awesome/fonts/fontawesome-webfont.ttf',
    '.npm/package/node_modules/font-awesome/fonts/fontawesome-webfont.woff',
    '.npm/package/node_modules/font-awesome/fonts/fontawesome-webfont.woff2',
    'fonts/Lato_Bold/Lato-Bold.eot',
    'fonts/Lato_Bold/Lato-Bold.svg',
    'fonts/Lato_Bold/Lato-Bold.ttf',
    'fonts/Lato_Bold/Lato-Bold.woff',
    'fonts/Lato_Bold_Italic/Lato-BoldItalic.eot',
    'fonts/Lato_Bold_Italic/Lato-BoldItalic.svg',
    'fonts/Lato_Bold_Italic/Lato-BoldItalic.ttf',
    'fonts/Lato_Bold_Italic/Lato-BoldItalic.woff',
    'fonts/Lato_Italic/Lato-Italic.eot',
    'fonts/Lato_Italic/Lato-Italic.svg',
    'fonts/Lato_Italic/Lato-Italic.ttf',
    'fonts/Lato_Italic/Lato-Italic.woff',
    'fonts/Lato_Light/Lato-Light.eot',
    'fonts/Lato_Light/Lato-Light.svg',
    'fonts/Lato_Light/Lato-Light.ttf',
    'fonts/Lato_Light/Lato-Light.woff',
    'fonts/Lato_Light_Italic/Lato-LightItalic.eot',
    'fonts/Lato_Light_Italic/Lato-LightItalic.svg',
    'fonts/Lato_Light_Italic/Lato-LightItalic.ttf',
    'fonts/Lato_Light_Italic/Lato-LightItalic.woff',
    'fonts/Lato_Regular/Lato-Regular.eot',
    'fonts/Lato_Regular/Lato-Regular.svg',
    'fonts/Lato_Regular/Lato-Regular.ttf',
    'fonts/Lato_Regular/Lato-Regular.woff',
    'fonts/Merriweather_Light/Merriweather-Light.eot',
    'fonts/Merriweather_Light/Merriweather-Light.svg',
    'fonts/Merriweather_Light/Merriweather-Light.ttf',
    'fonts/Merriweather_Light/Merriweather-Light.woff',
    'images/bg-header-footer-lg.png'
  ], 'client');
});

Package.onTest(function (api) {
});
